dubbo:
  registry:
    address: zookeeper://192.168.184.188:2181
  application:
    name: stu-provider
  protocol:
    port: -1
  consumer:
    check: false

spring:
  datasource:
    url: jdbc:mysql:///stu?serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
